name: Generate Doxygen Docs

on:
  push:
    branches: ["main"]
    tags:
      - '*.*.*'  # Ejecutar el workflow cuando se empuje un tag que siga el patrón de versiones (X.X.X)
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
	
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sudo apt-get update
          sudo apt-get install -y libfmt-dev libopencv-dev libgdal-dev libproj-dev libboost-all-dev
      
      - name: Install Doxygen
        if: startsWith(github.ref, 'refs/tags/')
        run: sudo apt-get install doxygen graphviz -y
      - name: Install Doxygen
        if: startsWith(github.ref, 'refs/tags/')
        run: sudo apt-get install doxygen graphviz -y		
      - name: Generate Doxyfile with CMake
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir build
          cd build
          cmake .. -DWITH_OPENCV=ON \
                   -DWITH_GDAL=ON \
                   -DWITH_PROJ=ON \
                   -DBUILD_APPS=OFF \
                   -DBUILD_TEST=OFF \
                   -DBUILD_DOC=ON
          cmake --build . --target doc
		  
      - name: Generate Doxygen documentation
        run: doxygen ./build/doc/Doxyfile		  
  
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name }}
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: false
          disable_nojekyll: true
